CREATE TABLE Roles
(	
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Roles_PK PRIMARY KEY(ID),
	CONSTRAINT Roles_NAME UNIQUE(NAME)
);

CREATE TABLE Genres
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Genres_PK PRIMARY KEY(ID),
	CONSTRAINT Genres_NAME UNIQUE(NAME)
);

CREATE TABLE Types
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Types_PK PRIMARY KEY(ID),
	CONSTRAINT Types_NAME UNIQUE(NAME)
);

CREATE TABLE Languages
( 
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Languages_PK PRIMARY KEY(ID),
	CONSTRAINT Lanugages_NAME UNIQUE(NAME)

);

CREATE TABLE Bands
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Bands_PK PRIMARY KEY(ID),
	CONSTRAINT Bands_NAME UNIQUE(NAME)
);

CREATE TABLE Labels
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Labels_PK PRIMARY KEY(ID),
	CONSTRAINT Labels_NAME UNIQUE(NAME)
);

CREATE TABLE Artists
(	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	ID_ROLES int,
	CONSTRAINT Artist_PK PRIMARY KEY(ID),
	CONSTRAINT Artists_NAME UNIQUE(NAME),
	CONSTRAINT Artists_Roles_FK FOREIGN KEY (ID_ROLES) REFERENCES Roles(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE CDs
(
	 ID INT NOT NULL,
	 NAME VARCHAR(50) NOT NULL,
	 ID_BAND INT,
	 ID_ARTIST INT,
	 ID_LABEL INT,
	 COVER VARCHAR(100), 
	 YR_OF_RLS INT,
	 ID_TYPE INT NOT NULL,
	 ID_GENRE INT,
	 CONSTRAINT CDs_PK PRIMARY KEY(ID),
	 CONSTRAINT CDs_ID_Band_FK FOREIGN KEY (ID_BAND) REFERENCES Bands(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	 CONSTRAINT CDs_ID_Label_FK FOREIGN KEY (ID_LABEL) REFERENCES Labels(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	 CONSTRAINT CDs_ID_Type_FK FOREIGN KEY (ID_TYPE) REFERENCES Types(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	 CONSTRAINT CDs_ID_Genre_FK FOREIGN KEY (ID_GENRE) REFERENCES Genres(ID) ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE TABLE Songs
(	ID INT NOT NULL,
	ID_CDs INT NOT NULL,
	NO_TRACK INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DURATION_M INT,
	DURATION_S INT,
	ID_GENRE INT,
	ID_LANGUAGE_1 INT,
	ID_LANGUAGE_2 INT,
	CONSTRAINT Songs_PK PRIMARY KEY(ID),
	-- CONSTRAINT Songs_Language_Unique UNIQUE(ID_LANGUAGE_1,ID_LANGUAGE_2), -- plain wrong
	CONSTRAINT Songs_CDTrack_Unique UNIQUE(ID_CDs, NO_TRACK),
	CONSTRAINT Songs_ID_CDs_FK FOREIGN KEY (ID_CDs) REFERENCES CDs(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT Songs_ID_Genre_FK FOREIGN KEY (ID_GENRE) REFERENCES Genres(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Songs_ID_Languages_FK FOREIGN KEY (ID_LANGUAGE_1) REFERENCES Languages(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Songs_ID_Languages2_FK FOREIGN KEY (ID_LANGUAGE_2) REFERENCES Languages(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Authors
(
	ID INT NOT NULL,
	ID_BAND INT,
	ID_ARTIST INT NOT NULL,
	ID_SONG INT NOT NULL,
	ID_ROLES INT,
	NOTES VARCHAR(500),
	CONSTRAINT Authors_PK PRIMARY KEY(ID),
	CONSTRAINT Authors_Band_FK FOREIGN KEY (ID_BAND) REFERENCES Bands(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Authors_Artists_FK FOREIGN KEY (ID_ARTIST) REFERENCES Artists(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Authors_Song_FK FOREIGN KEY (ID_SONG) REFERENCES Songs(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Authors_Role_FK FOREIGN KEY (ID_ROLES) REFERENCES Roles(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE CDs ADD CONSTRAINT CDs_ID_Artists_FK FOREIGN KEY (ID_ARTIST) REFERENCES Artists(ID) ON UPDATE CASCADE ON DELETE SET NULL;
